# Generated by Django 3.1.7 on 2021-03-11 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100)),
                ('estate_type', models.CharField(choices=[('House', 'House'), ('Land', 'Land'), ('Apartment', 'Apartment'), ('Villa', 'Villa')], max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('location', models.CharField(choices=[('New Valley', 'New Valley'), ('Matruh', 'Matruh'), ('Red Sea', 'Red Sea'), ('Giza', 'Giza'), ('South Sinai', 'South Sinai'), ('North Sinai', 'North Sinai'), ('Suez', 'Suez'), ('Beheira', 'Beheira'), ('Helwan', 'Helwan'), ('Sharqia', 'Sharqia'), ('Dakahlia', 'Dakahlia'), ('Kafr el-Sheikh', 'Kafr el-Sheikh'), ('Alexandria', 'Alexandria'), ('Monufia', 'Monufia'), ('Minya', 'Minya'), ('Gharbia', 'Gharbia'), ('Faiyum', 'Faiyum'), ('Qena', 'Qena'), ('Asyut', 'Asyut'), ('Sohag', 'Sohag'), ('Ismailia', 'Ismailia'), ('Beni Suef', 'Beni Suef'), ('Qalyubia', 'Qalyubia'), ('Aswan', 'Aswan'), ('Damietta', 'Damietta'), ('Cairo', 'Cairo'), ('Port Said', 'Port Said'), ('Luxor', 'Luxor'), ('6th of October', '6th of October')], max_length=100)),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('Sale', 'Sale'), ('Rent', 'Rent')], max_length=100)),
                ('area', models.IntegerField(default='100')),
                ('bed', models.IntegerField(default='2')),
                ('room', models.IntegerField(default='2')),
                ('bath', models.IntegerField(default='1')),
                ('garag', models.IntegerField(default='0')),
            ],
        ),
    ]
