# Generated by Django 3.1.7 on 2021-03-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_estate_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='price',
            field=models.IntegerField(default='10000'),
        ),
    ]
