# Generated by Django 3.1.7 on 2021-03-12 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_estate_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='estate',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
